# Linear Algebra

In [1]:
#importing libraries
import numpy
import numpy as np
import numpy.linalg as nla
import scipy.linalg as sla
import matplotlib.pyplot as plt

## Matrices

* Matrices are two-dimensional lists of numbers
* Think of matrices as vectors of vectors
* On a more abstract level, matrices describe **linear mappings** from one vector space to another
* Data are frequently given in a matrix form, so the study of matrices comes naturally

## Creating matrices

In [2]:
# creating matrices using numpy.array

A = np.array([[1, 2], [3, 4], [5, 6]])

B = np.array([[-1, 0, 1], [0, 2, 1], [3, -1, -2]])

C = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])

D = np.array([[5, -2, 4], [1, 0, -1]])

O = np.zeros([3,3])

I = np.eye(3)


matrix_list = [A, B, C, D, O, I]
for matrix in matrix_list:
    print(matrix)
    print()

[[1 2]
 [3 4]
 [5 6]]

[[-1  0  1]
 [ 0  2  1]
 [ 3 -1 -2]]

[[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]

[[ 5 -2  4]
 [ 1  0 -1]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [7]:
# Matrix dimensionality
# (note the difference between .shape and .size)
for matrix in matrix_list:
    print(matrix.shape)
    print()

(3, 2)

(3, 3)

(3, 3)

(2, 3)

(3, 3)

(3, 3)



## Operations with matrices
* First we take a look at operations that are performed by operating on components

In [10]:
# Component-wise operations
# These are possible only if the matrices have same dimensionality

summ = B + C

diff = B - C

c_prod = B * C # Hadamard product -> useful with convolutional neural networks

quot = B / C

scalar_mult = 0.5 * A

operations_list = [summ, diff, c_prod, quot, scalar_mult]
for matrix in operations_list:
    print(matrix)
    print()

[[ 0 -2  4]
 [-4  7 -5]
 [10 -9  7]]

[[ -2   2  -2]
 [  4  -3   7]
 [ -4   7 -11]]

[[ -1   0   3]
 [  0  10  -6]
 [ 21   8 -18]]

[[-1.         -0.          0.33333333]
 [-0.          0.4        -0.16666667]
 [ 0.42857143  0.125      -0.22222222]]

[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]



In [11]:
# Multiple operations:
print(3*B - 2*C - I)

[[ -6.   4.  -3.]
 [  8.  -5.  15.]
 [ -5.  13. -25.]]


* Matrix transposition: restructuring a matrix by switching rows and columns. If $A$ is the matrix, then $A^T$ is its transpose
* Trace of a matrix: sum of the elements along the diagonal of a matrix. We label the trace by $\mathrm{tr}(A)$
* Determinant of a matrix: a number assigned to a **square** matrix, labeled by $\det(A)$

In [16]:
# Matrix transposition
print(A)
print()
print(A.T)

# Trace
print('trace(A) = ', np.trace(A))

# Determinant
print('det(B) = ', nla.det(B))
print('det(A) = ', nla.det(A)) # throws an error

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]
trace(A) =  5
det(B) =  -2.9999999999999996


LinAlgError: Last 2 dimensions of the array must be square

* Next we take look at **matrix multiplication** which is not performed component-wise
* The *actual* matrix multiplication is performed by dot-multiplying rows from the first multiplier by columns from the second multiplier
* Matrix multiplication is only possible when multiplying (m, p) by (p, n) matrices; the product will have a dimension (m, n)

In [22]:
# Matrix multiplication
# (unlike number multiplication, matrix multiplication is not commutiative, even when it can be performed)
print('B = \n', B)
print('\nC = \n', C)
print('\nB*C = \n', B.dot(C)) # B @ C

B = 
 [[-1  0  1]
 [ 0  2  1]
 [ 3 -1 -2]]

C = 
 [[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]

B*C = 
 [[ 6 -6  6]
 [-1  2 -3]
 [-7  5 -3]]


In [25]:
print('A = \n', A)
print('\nD = \n', D)
print('\nA*D = \n', A@D)
print('\nD*A = \n', D@A)

A = 
 [[1 2]
 [3 4]
 [5 6]]

D = 
 [[ 5 -2  4]
 [ 1  0 -1]]

A*D = 
 [[  7  -2   2]
 [ 19  -6   8]
 [ 31 -10  14]]

D*A = 
 [[19 26]
 [-4 -4]]


## Types of matrices

* Square
* Symmetric
* Triangular
* Diagonal
* Orthogonal

In [30]:
# Square matrix: dimension (n, n)


# Symmetric matrix: A = A.T
Sym = np.array([[1, 3], [3, 4]])
print(Sym)
print(Sym.T)

# Triangular matrix: zeros above the diagonal (lower-triangular) or below the diagonal (upper-triangular)
# Diagonal matrix: zeros everywhere, except (possibly) on the diagonal


# Identity matrix: diagonal matrix with ones on the diagonal
# (can be generated with numpy.eye or numpy.identity)
print(I)
print()

# Orthogonal matrix: Q.dot(Q.T) = I
Q = np.array([[1/3, -2/3, 2/3], [2/3, -1/3, -2/3], [2/3, 2/3, 1/3]])
print(Q)
print(Q.dot(Q.T))
print()


[[1 3]
 [3 4]]
[[1 3]
 [3 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 0.33333333 -0.66666667  0.66666667]
 [ 0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667  0.66666667  0.33333333]]
[[1.00000000e+00 2.46716228e-17 1.54197642e-17]
 [2.46716228e-17 1.00000000e+00 1.23358114e-17]
 [1.54197642e-17 1.23358114e-17 1.00000000e+00]]



## Inverse matrices of square matrices
* The identity matrix acts as 'one' or 'unit' in matrix multiplication: has no effect under the operation
* This is similar to reciprocal numbers: e.g.   $2 \cdot \frac{1}{2} = 2 \cdot 2^{-1} = 1$
* In general, if $a \neq 0$, then  $a \cdot \frac{1}{a} = a \cdot a^{-1} = 1$
* In context of matrices: given a square matrix $M$, **if** there exists a matrix $M'$ such that $M\cdot M' = M' \cdot M = I$, then we call the matrix $M$ invertible matrix, and the matrix $M'$ -- inverse of $M$. The inverse matrix is most frequently labelled as $M^{-1}$.
* Note that the inverse matrix might not exist!

In [38]:
# Inverse matrix: use np.inv()
M = np.array([[-1, 3/2], [1, -1]])
print('M = \n', M)
print('det(M) = ', nla.det(M))
M_inv = nla.inv(M)
print('M_inv = \n', M_inv)


# numpy.linalg.det can be used to see if a matrix is invertible by calculating its determinant
# if det(M) = 0, then M is not invertible
N = np.array([[5, -5, 0], [0, 0, 0], [3, -3, 2]]) #not invertible
print('N= \n', N)
print('det(N) = ', nla.det(N))
N_inv = nla.inv(N) # throws an error, the matrix is singular (not invertible)

M = 
 [[-1.   1.5]
 [ 1.  -1. ]]
det(M) =  -0.5
M_inv = 
 [[2. 3.]
 [2. 2.]]
N= 
 [[ 5 -5  0]
 [ 0  0  0]
 [ 3 -3  2]]
det(N) =  0.0


LinAlgError: Singular matrix

In [36]:
M.dot(M_inv)
M_inv.dot(M)

array([[1., 0.],
       [0., 1.]])

### Solving systems of linear equations using matrices
Every system of linear equations can be represented as a **matrix equation**. For example, the system:
\begin{equation}
\left\{
\begin{array}{rcl}
    2 x_1 + 3 x_2 & = & 6\\
    x_1 - x_2 & = & -2
\end{array}
\right.
\end{equation}

can be represented as a matrix equation $Ax = b$ where:
\begin{equation}
A = 
    \begin{bmatrix}
    2 & 3\\
    1 & -1
    \end{bmatrix}
\qquad\qquad
x = 
    \begin{bmatrix}
    x_1\\
    x_2
    \end{bmatrix}
\qquad\qquad
b = 
    \begin{bmatrix}
    6\\
    -2
    \end{bmatrix}
\end{equation}

This system can then be solved by using the inverse of the matrix $A$ to get the solution $x$ by calculating:
\begin{equation}x = A^{-1}b\end{equation}

In [41]:
# Solving a system of equations using inverse matrices
A = np.array([[2, 3], [1, -1]])
b = np.array([6, -2])

x = nla.inv(A).dot(b)

print(x)

[-2.22044605e-16  2.00000000e+00]


## Pseudoinverse matrices for non-square matrices
* The concept of an inverse matrix is defined only for square matrices. For non-square matrices we define another concept, closely paralleling the inverse matrix.
* For non-square matrices we introduce the concept os a **pseudoinverse matrix**. The full name is **Moore-Penrose inverse matrix**.
* Given a matrix $A$, the its pseudoinverse $A^+$ satisfies the following conditions:
\begin{equation}
\begin{array}{rcl}
    A A^+ A & = & A\\
    A^+ A A^+ & = & A^+\\
\end{array}
\end{equation}
Additionally, both $A^+ A$ and $AA^+$ are symmetric. The first product is always the identity matrix of an appropriate order, but the second product is not an identity matrix.

In [45]:
# Pseudoinverse of a non-square matrix
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
M_pinv = nla.pinv(M)

# print('M_pinv = \n', M_pinv)

M@M_pinv@M

M_pinv@M@M_pinv

array([[-1.0000000e+00, -5.0000000e-01, -1.5959456e-17,  5.0000000e-01],
       [ 8.5000000e-01,  4.5000000e-01,  5.0000000e-02, -3.5000000e-01]])

### Solving overdetermined systems of linear equations using pseudoinverse matrices
* When a linear system has more equations than it has variables, we call it **overdetermined** (similarly, if there are less equations than variables, we call it **underdetermined**)
* Overdetermined systems appear regularly in **least squares regression**, so it is natural to look at methods of solving
* An overdetermined system does not always have a solution: sometimes the "solution" or pseudosolution is a set of values which are as close to being a solution to the system as possible.
* If the overdetermined system is given by $Ax = b$, then the pseudosolution $\tilde{x}$ is given by
\begin{equation} \tilde{x} = A^+ b \end{equation}

#### Example: the system has an exact solution
Solve the following system:
\begin{equation}
\left\{
\begin{array}{rcl}
    x_1 + x_2 &=& 2\\
    2 x_1 - x_2 &=& 1\\
    -5 x_1 + 7 x_2 &=& 2\\
    3 x_1 + 5 x_2 &=&8
\end{array}
\right.
\end{equation}

In [46]:
# System has an exact solution
A = np.array([[1, 1], [2, -1], [-5, 7], [3, 5]])
b = np.array([2, 1, 2, 8])

x = nla.pinv(A).dot(b)
x

array([1., 1.])

#### Example: the system does not have an exact solution
Solve the following system:
\begin{equation}
\left\{
\begin{array}{rcl}
    x_1 + 3 x_2 &=& 17\\
    5 x_1 + 7 x_2 &=& 19\\
    11 x_1 + 13 x_2 &=& 23
\end{array}
\right.
\end{equation}

In [48]:
# System does not have an exact solution
A = np.array([[1, 3], [5, 7], [11, 13]])
b = np.array([17, 19, 23])

x = nla.pinv(A).dot(b)

print(A.dot(x))

[16.84210526 19.26315789 22.89473684]


## Practice Assignment:
* Write a function *solve_system* that solves the system of linear equations $Ax=b$ using inverse/pseudoinverse matrices
* The function takes two input arguments: a matrix $A$ of shape (m, n), and a vector $b$ of size m
* The function first decides whether to use inverse or pseudoinverse matrix (based on the size of the input matrix), then calculates and prints the solution (if there is one) or the pseudosolution
* Apart from the (pseudo)solution, the function should print if the given vector is an exact solution or a pseudosolution.
* You can choose if the function is only going to print outputs, or return them as output variables (either way is ok, as long as the function works)

In [ ]:
# Function that solves linear systems using (pseudo)inverse matrices

def solve_system(A, b):
    