In [1]:
import numpy as np
import pandas as pd

In [3]:
# Create a boolean numpy array for the odd elements of the following array arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Now use that boolean array to get a the array containing only the odd elements.

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [13]:
# Create a 5X3 random integer array using np.random.randint of numbers between 1 and 10.
# - Compute the sum along rows and columns.
# - Compute the maximum and minimum along rows and columns.

mat = np.random.randint(1, 11, size=(5,3))
print(mat)

print("Sum of each column:")
print(np.sum(mat, axis=0))
print("Sum of each row:")
print(np.sum(mat, axis=1))

print("Max of each column:")
print(np.max(mat, axis=0))
print("Min of each column:")
print(np.min(mat, axis=0))

print("Max of each row:")
print(np.max(mat, axis=1))
print("Min of each row:")
print(np.min(mat, axis=1))

[[6 4 1]
 [5 8 6]
 [7 4 3]
 [1 8 7]
 [6 2 2]]
Sum of each column:
[25 26 19]
Sum of each row:
[11 19 14 16 10]
Max of each column:
[7 8 7]
Min of each column:
[1 2 1]
Max of each row:
[6 8 7 8 6]
Min of each row:
[1 5 3 1 2]


In [16]:
# From the array created with np.arange(20) extract a smaller array of elements between 7 and 13 using boolean indexing.

arr2 = np.arange(20)
print(arr2)

print(arr2[(arr2 > 7) & (arr2 < 13)])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 8  9 10 11 12]


In [31]:
# Use np.random.randint(1, 11, 1000) to get 1000 numbers between and 11.
# Read about np.unique and its argument return_counts. Use it to get the nubmer of occurences (count) of each number.
# Now read about np.argmax and how you can use it to find the number which has occured most often.

a = np.random.randint(1, 11, 1000)
a

unique, counts = np.unique(a, return_counts=True)
print(unique, counts)

m = np.argmax(counts)
print(m)

print(unique[m])

[ 1  2  3  4  5  6  7  8  9 10] [113  96 112 101  95  94  91 102 110  86]
0
1


In [38]:
# Create two pandas Series from the following lists [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]
# Now add, subtract, multiplye and divide them

ser1 = pd.Series([2, 4, 6, 8, 10])
ser2 = pd.Series([1, 3, 5, 7, 9])

ser3 = ser1 + ser2
ser4 = ser1 - ser2
ser5 = ser1 * ser2
ser6 = ser1 / ser2

ser3, ser4, ser5, ser6

(0     3
 1     7
 2    11
 3    15
 4    19
 dtype: int64,
 0    1
 1    1
 2    1
 3    1
 4    1
 dtype: int64,
 0     2
 1    12
 2    30
 3    56
 4    90
 dtype: int64,
 0    2.000000
 1    1.333333
 2    1.200000
 3    1.142857
 4    1.111111
 dtype: float64)

In [40]:
# Create two pandas Series from the following lists [1, 2, 3, 4, 5] and [4, 5, 6, 7, 8]
# Read about the isin() function. Use it to get the items of series A not present in series B.
# Hint: also use the ~ for negative reverse

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

print(s1)
print(s2)

p = s1.isin(s2)

print(p)

s1[p]
s1[~p]

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    4
1    5
2    6
3    7
4    8
dtype: int64
0    False
1    False
2    False
3     True
4     True
dtype: bool


0    1
1    2
2    3
dtype: int64

In [44]:
# Create 6x4 DataFrame with random numbers, row indexes from R1 to R6 and column indexes from C1 to C4.
# Access any column of your choice by name.
# Access multiple columns of your choice by name.
# Access any row of your choice by name.
# Access any row of your choice by index.

rows = ["R" + str(x) for x in range(1,7)]
cols = ["C" + str(x) for x in range(1, 5)]

df = pd.DataFrame(data=np.random.randint(1,100, size= (6,4)), index=["R1","R2","R3","R4","R5","R6"], columns = ["C1", "C2", "C3", "C4"])
print(df)

df[['C3', 'C1']]

df.loc["R3"]

df.iloc[0]

# Create new column in the DataFrame by multiplying two columns of your choice.
# Then try to remove this column completely from the active DataFrame.

df['My column'] = df['C1'] * df['C3']
df
df.drop('My column', inplace=True, axis= 1)

# Query the rows in DataFrame where the values in column C1 are bigger than the values in column C4 and show only these 2 columns.
df.query('C1 > C4')[['C1', 'C4']]

    C1  C2  C3  C4
R1  60   7  57  46
R2  33  69  91  28
R3  91  33  73  74
R4  73  79   1  25
R5  39  90  62  47
R6  42   6  79  41


C1  C4
R1  60  46
R2  33  28
R3  91  74
R4  73  25
R6  42  41